// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallLLMAPI(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CallLLMAPI'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CancelShotgunContextGeneration() {
  return window['go']['main']['App']['CancelShotgunContextGeneration']();
}

export function EstimateCost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EstimateCost'](arg1, arg2, arg3, arg4);
}

export function EstimateTokens(arg1) {
  return window['go']['main']['App']['EstimateTokens'](arg1);
}

export function GeneratePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GeneratePrompt'](arg1, arg2, arg3, arg4);
}

export function GetCustomIgnoreRules() {
  return window['go']['main']['App']['GetCustomIgnoreRules']();
}

export function GetCustomPromptRules() {
  return window['go']['main']['App']['GetCustomPromptRules']();
}

export function GetJobStatuses() {
  return window['go']['main']['App']['GetJobStatuses']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ReadFileContents(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContents'](arg1, arg2);
}

export function RequestShotgunContextGeneration(arg1, arg2) {
  return window['go']['main']['App']['RequestShotgunContextGeneration'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCustomIgnoreRules(arg1) {
  return window['go']['main']['App']['SetCustomIgnoreRules'](arg1);
}

export function SetCustomPromptRules(arg1) {
  return window['go']['main']['App']['SetCustomPromptRules'](arg1);
}

export function SetUseCustomIgnore(arg1) {
  return window['go']['main']['App']['SetUseCustomIgnore'](arg1);
}

export function SetUseGitignore(arg1) {
  return window['go']['main']['App']['SetUseGitignore'](arg1);
}

export function SplitShotgunDiff(arg1, arg2) {
  return window['go']['main']['App']['SplitShotgunDiff'](arg1, arg2);
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StartupTest(arg1) {
  return window['go']['main']['App']['StartupTest'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}

export function WSLClipboardSetText(arg1) {
  return window['go']['main']['App']['WSLClipboardSetText'](arg1);
}
